Algoritmo " recepção"

Var
nome, email : caractere
idade :inteiro

Inicio
escreval("Boa tarde! Digite o seu nome: ")
leia(nome)
limpatela()

escreval("Digite a sua idade: ")
leia(idade)
limpatela()

escreval("Digite o seu email: ")
leia(email)
limpatela()

escreval("Cadrastro efetuado com sucesso")
escreval("************************")
escreval("Usuario : ",nome)
escreval("Idade : ", idade)
escreval("Email: ", email)
escreval("**********************")
Fimalgoritmo